import type { ExecutiveProfile } from "./types";

export const executiveRoster: ExecutiveProfile[] = [
  {
    id: "ceo",
    name: "Elena Vasquez",
    role: "CEO Agent",
    trait: "Decisive",
    quote: "Give me the one metric that matters and I'll tell you if this works.",
    bio: "Weighs vision against execution risk. Pushes founders to state a single thesis before anything else is discussed.",
    focusAreas: ["Vision", "Execution risk", "Founder-market fit"],
    presence: "active",
    sessionsRun: 412,
    agreementRate: 68,
  },
  {
    id: "cto",
    name: "Priya Nair",
    role: "CTO Agent",
    trait: "Builds fast",
    quote: "I don't care about your roadmap. I care if it ships.",
    bio: "Stress-tests technical feasibility and team capability. Consistently the board's fastest to flag scope that won't ship on time.",
    focusAreas: ["Technical feasibility", "Team capability", "Build vs. buy"],
    presence: "speaking",
    sessionsRun: 398,
    agreementRate: 61,
  },
  {
    id: "cfo",
    name: "Marcus Webb",
    role: "CFO Agent",
    trait: "Risk-averse",
    quote: "Show me the burn rate before you show me the vision.",
    bio: "The board's most conservative vote. Every model gets pressure-tested against a worst-case runway scenario first.",
    focusAreas: ["Unit economics", "Runway", "Capital efficiency"],
    presence: "active",
    sessionsRun: 412,
    agreementRate: 47,
  },
  {
    id: "cmo",
    name: "Aiko Tanaka",
    role: "CMO Agent",
    trait: "Story-driven",
    quote: "Nobody invests in a feature. They invest in a narrative.",
    bio: "Evaluates whether the pitch has a story an investor — or a customer — can repeat in one sentence.",
    focusAreas: ["Positioning", "Go-to-market", "Brand narrative"],
    presence: "idle",
    sessionsRun: 375,
    agreementRate: 72,
  },
  {
    id: "vc",
    name: "Jonah Kessler",
    role: "VC Agent",
    trait: "Term-sheet minded",
    quote: "What's the exit, and who's already said no to this?",
    bio: "Runs every pitch through the lens of a real fundraising round: comparables, dilution, and the honest odds of a Series A.",
    focusAreas: ["Fundability", "Comparables", "Round structure"],
    presence: "idle",
    sessionsRun: 412,
    agreementRate: 54,
  },
  {
    id: "legal",
    name: "Diane Okafor",
    role: "Legal Agent",
    trait: "Reads the fine print",
    quote: "Compliance isn't a blocker. It's what keeps you fundable later.",
    bio: "Flags regulatory and IP exposure early, before it becomes a diligence blocker for a real investor.",
    focusAreas: ["Regulatory exposure", "IP", "Cap table hygiene"],
    presence: "idle",
    sessionsRun: 289,
    agreementRate: 59,
  },
  {
    id: "research",
    name: "Nadia Petrov",
    role: "Research Agent",
    trait: "Evidence-first",
    quote: "That's a claim. Where's the data behind it?",
    bio: "Cross-checks every market-size and competitor claim in the pitch against independent sources before the board votes.",
    focusAreas: ["Market sizing", "Competitive landscape", "Source verification"],
    presence: "idle",
    sessionsRun: 340,
    agreementRate: 65,
  },
  {
    id: "growth",
    name: "Théo Marchand",
    role: "Growth Agent",
    trait: "Growth-obsessed",
    quote: "Retention is the pitch. Everything else is acquisition theater.",
    bio: "Pushes past vanity metrics to the retention curve underneath — usually the board's toughest cross-examiner on traction slides.",
    focusAreas: ["Retention", "Growth loops", "Traction quality"],
    presence: "idle",
    sessionsRun: 301,
    agreementRate: 58,
  },
  {
    id: "tech_expert",
    name: "Dr. Meera Pillai",
    role: "Technical Feasibility Assessor",
    trait: "Builds for government scale",
    quote: "Slides don't run in production. Where's the working software?",
    bio: "Evaluates whether the startup's proposed solution is technically mature enough for a government pilot. Blunt about prototype-vs-production gaps.",
    focusAreas: ["Technical feasibility", "Architecture", "Scalability"],
    presence: "active",
    sessionsRun: 120,
    agreementRate: 50,
  },
  {
    id: "finance_auditor",
    name: "Ramesh Iyer",
    role: "Government Finance Auditor",
    trait: "Follows the rulebook",
    quote: "Does this comply with GFR 2017? If not, we can't pay you.",
    bio: "Verifies that the startup's commercials comply with GFR 2017 norms and that the proposed pilot cost is value-for-money. The board's most conservative voice on public expenditure.",
    focusAreas: ["GFR 2017 Compliance", "Value for Money", "Unit Economics"],
    presence: "idle",
    sessionsRun: 230,
    agreementRate: 45,
  },
  {
    id: "legal_compliance",
    name: "Sunita Rao",
    role: "Legal Advisor",
    trait: "Risk identifier",
    quote: "Data localisation is not a suggestion. It's the law.",
    bio: "Surfaces IP ownership risks, data localisation obligations under PDPB 2023, GeM compliance gaps, and regulatory approvals.",
    focusAreas: ["Data Localisation", "IP Rights", "Regulatory Approvals"],
    presence: "idle",
    sessionsRun: 180,
    agreementRate: 55,
  },
  {
    id: "impact_assessor",
    name: "Vikram Nair",
    role: "Social Impact Assessor",
    trait: "Citizen-first",
    quote: "How does this actually help the average citizen in a rural district?",
    bio: "Evaluates the real-world benefit to the department and citizens. Pushes back on solutions that are technically impressive but operationally impractical.",
    focusAreas: ["Citizen Impact", "Operational Feasibility", "Adoption Barriers"],
    presence: "active",
    sessionsRun: 150,
    agreementRate: 60,
  },
  {
    id: "risk_officer",
    name: "Dr. Anjali Desai",
    role: "Risk Officer",
    trait: "Worst-case planner",
    quote: "What happens to our data if you go out of business tomorrow?",
    bio: "Scores the pilot's failure modes — vendor lock-in, data breach, citizen data misuse, and startup discontinuity risk — and proposes contractual mitigations.",
    focusAreas: ["Vendor Lock-in", "Data Privacy", "Continuity Risk"],
    presence: "idle",
    sessionsRun: 160,
    agreementRate: 65,
  }
];
